### ISSUE TITLE
Zombie derender issue

### ISSUE THREAD

**Issue by TarshenNaidoo** [TarshenNaidoo/CGVProjectRed#1]
For some reason, the zombie models created in blender and exported as glb files extend past the bounds of their hitbox causing the renderer to derender them even when the models (but not the hitbox) are still in view. I'v done a workaround by importing them to threejs.org/editor, and resizing but the only supported export is json which removes animation. Thus, zombies imported into the game lack animation and poses. We'll have to find away to resize them and export them as glb files

**Comment by Masingita01** [comment]
The solution, in case you guys get the problem, is here: https://blender.stackexchange.com/a/178642/96522. So in our project, where you see "model" in the code, you change it to the name assigned e.g. zombie.traverse(...);
